version: "3.9"
services:
  web:
    build: ./blog
    command: gunicorn blog.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
  nginx:
    image: nginx:latest
    volumes:
      - /var/:/usr/share/nginx/html:ro
    expose:
      - 8000:80
